"""Add description in products table

Revision ID: 4d8bbf5b3ec7
Revises: 432d6fd1b1a5
Create Date: 2021-12-22 12:15:31.428006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d8bbf5b3ec7'
down_revision = '432d6fd1b1a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('description', sa.Text(), nullable=True))
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('products', 'description')
    # ### end Alembic commands ###
